
from hdlite import Signal as sig
from hdlite.Component import *

# Work in progress...

# pp 3-181

class Sigma7CPU(Component):
    def __init__(self, reset, clock, C, S):
        super().init(self)
        self.reset = reset
        self.clock = clock
        self.C = C
        self.S = S
        self.O = sig.Vector(7)
        self.O1 = sig.Signal()
        self.O2 = sig.Signal()
        self.O3 = sig.Signal()
        self.O4 = sig.Signal()
        self.O5 = sig.Signal()
        self.O6 = sig.Signal()
        self.O7 = sig.Signal()
        self.NO1 = sig.Signal()
        self.NO2 = sig.Signal()
        self.NO3 = sig.Signal()
        self.NO4 = sig.Signal()
        self.NO5 = sig.Signal()
        self.NO6 = sig.Signal()
        self.NO7 = sig.Signal()
        self.OU0 = sig.Signal()
        self.OU1 = sig.Signal()
        self.OU2 = sig.Signal()
        self.OU3 = sig.Signal()
        self.OU4 = sig.Signal()
        self.OU5 = sig.Signal()
        self.OU6 = sig.Signal()
        self.OU7 = sig.Signal()
        self.OL0 = sig.Signal()
        self.OL1 = sig.Signal()
        self.OL2 = sig.Signal()
        self.OL3 = sig.Signal()
        self.OL4 = sig.Signal()
        self.OL5 = sig.Signal()
        self.OL6 = sig.Signal()
        self.OL7 = sig.Signal()
        self.OL8 = sig.Signal()
        self.OL9 = sig.Signal()
        self.OLA = sig.Signal()
        self.OLB = sig.Signal()
        self.OLC = sig.Signal()
        self.OLD = sig.Signal()
        self.OLE = sig.Signal()
        self.OLF = sig.Signal()

        self.FUAD = sig.Signal()
        self.FUANLZ = sig.Signal()
        self.FUAWM = sig.Signal()

        self.FUBAL = sig.Signal()
        self.FUCB = sig.Signal()
        self.FUCI = sig.Signal()
        self.FUCLR = sig.Signal()
        self.FUCS = sig.Signal()
        self.FUCVS = sig.Signal()
        self.FUEOR = sig.Signal()
        self.FUEXU = sig.Signal()
        self.FULAD = sig.Signal()
        self.FULCD = sig.Signal()
        self.FULD = sig.Signal()
        self.FUINT = sig.Signal()
        self.FULRP = sig.Signal()
        self.FULS = sig.Signal()
        self.FUMMC = sig.Signal()
        self.FUMTB = sig.Signal()
        self.FUMTH = sig.Signal()
        self.FUMTW = sig.Signal()
        self.FUSTD = sig.Signal()
        self.FUSTH = sig.Signal()
        self.FUOR = sig.Signal()
        self.FUSTS = sig.Signal()
        self.FUWAIT = sig.Signal()
        self.FUXW = sig.Signal()

        self.FABC = sig.Signal()
        self.FABOX = sig.Signal()
        self.FABR = sig.Signal()
        self.FACAL = sig.Signal()
        self.FACV = sig.Signal()
        self.FADE = sig.Signal()
        self.FADIV = sig.Signal()
        self.FADW = sig.Signal()
        self.FAFL = sig.Signal()
        self.FAFLD = sig.Signal()
        self.FAFLM = sig.Signal()
        self.FAFRR = sig.Signal()
        self.FAFRR_1 = sig.Signal()
        self.FAILL = sig.Signal()
        self.FAIM = sig.Signal()
        self.FAIO = sig.Signal()
        self.FAMDSF = sig.Signal()
        self.FAMDSF_D = sig.Signal()
        self.FAMUL = sig.Signal()
        self.FANIMP = sig.Signal()
        self.FAPRIV = sig.Signal()
        self.FAPSD = sig.Signal()
        self.FARWD = sig.Signal()
        self.FAS1 = sig.Signal()
        self.FAS2 = sig.Signal()
        self.FAS3 = sig.Signal()
        self.FAS6 = sig.Signal()
        self.FAS7 = sig.Signal()
        self.FAS8 = sig.Signal()
        self.FAS9 = sig.Signal()
        self.FAS10 = sig.Signal()
        self.FAS11 = sig.Signal()
        self.FAS12 = sig.Signal()
        self.FAS13 = sig.Signal()
        self.FAS14 = sig.Signal()
        self.FAS15 = sig.Signal()
        self.FAS16 = sig.Signal()
        self.FAS17 = sig.Signal()
        self.FAS18 = sig.Signal()
        self.FAS19 = sig.Signal()
        self.FAS21 = sig.Signal()
        self.FAS22 = sig.Signal()
        self.FAS23 = sig.Signal()
        self.FAS24 = sig.Signal()
        self.FAS26 = sig.Signal()
        self.FASH = sig.Signal()
        self.FASHFL = sig.Signal()
        self.FASHFX = sig.Signal()
        self.FAST_1 = sig.Signal()
        self.FAW = sig.Signal()

    def run(self):
        self.O1 <<= self.O[6]
        self.O2 <<= self.O[5]
        self.O3 <<= self.O[4]
        self.O4 <<= self.O[3]
        self.O5 <<= self.O[2]
        self.O6 <<= self.O[1]
        self.O7 <<= self.O[0]
        self.NO1 <<= ~self.O[6]
        self.NO2 <<= ~self.O[5]
        self.NO3 <<= ~self.O[4]
        self.NO4 <<= ~self.O[3]
        self.NO5 <<= ~self.O[2]
        self.NO6 <<= ~self.O[1]
        self.NO7 <<= ~self.O[0]

        self.OU0 <<= self.NO1 & self.NO2 & self.NO3
        self.OU1 <<= self.NO1 & self.NO2 & self.O3
        self.OU2 <<= self.NO1 & self.O2 & self.NO3
        self.OU3 <<= self.NO1 & self.O2 & self.O3
        self.OU4 <<= self.O1 & self.NO2 & self.NO3
        self.OU5 <<= self.O1 & self.NO2 & self.O3
        self.OU6 <<= self.O1 & self.O2 & self.NO3
        self.OU7 <<= self.O1 & self.O2 & self.O3
        self.OL0 <<= self.NO4 & self.NO5 & self.NO6 & self.NO7
        self.OL1 <<= self.NO4 & self.NO5 & self.NO6 & self.NO7
        self.OL2 <<= self.NO4 & self.NO5 & self.O6 & self.NO7
        self.OL3 <<= self.NO4 & self.NO5 & self.O6 & self.O7
        self.OL4 <<= self.NO4 & self.O5 & self.NO6 & self.NO7
        self.OL5 <<= self.NO4 & self.O5 & self.NO6 & self.O7
        self.OL6 <<= self.NO4 & self.O5 & self.O6 & self.NO7
        self.OL7 <<= self.NO4 & self.O5 & self.O6 & self.O7
        self.OL8 <<= self.O4 & self.NO5 & self.NO6 & self.NO7
        self.OL9 <<= self.O4 & self.NO5 & self.NO6 & self.O7
        self.OLA <<= self.O4 & self.NO5 & self.O6 & self.NO7
        self.OLB <<= self.O4 & self.NO5 & self.O6 & self.O7
        self.OLC <<= self.O4 & self.O5 & self.NO6 & self.NO7
        self.OLD <<= self.O4 & self.O5 & self.NO6 & self.O7
        self.OLE <<= self.O4 & self.O5 & self.O6 & self.NO7
        self.OLF <<= self.O4 & self.O5 & self.O6 & self.O7

        self.FUAD <<= self.OU1 & self.OL0
        self.FUANLZ <<= self.OU4 & self.OL4
        self.FUAWM <<= self.OU6 & self.OL6

        self.FUBAL <<= self.OU6 & self.OLA
        self.FUCB <<= self.OU7 & self.OL1
        self.FUCI <<= self.OU2 & self.OL1
        self.FUCLR <<= self.OU3 & self.OL9
        self.FUCS <<= self.OU4 & self.OL5
        self.FUCVS <<= self.FACV & self.NO7
        self.FUEOR <<= self.OU4 & self.OL8
        self.FUEXU <<= self.OU6 & self.OU7
        self.FULAD <<= self.OU1 & self.OLB
        self.FULCD <<= self.OU1 & self.OLA
        self.FULD <<= self.OU1 & self.OL2
        self.FUINT <<= self.OU6 & self.OLB
        self.FULRP <<= self.OU2 & self.OLF
        self.FULS <<= self.OU4 & self.OLA
        self.FUMMC <<= self.OU6 & self.OLF
        self.FUMTB <<= self.OU7 & self.OL3
        self.FUMTH <<= self.OU5 & self.OL3
        self.FUMTW <<= self.OU3 & self.OL3
        self.FUSTD <<= self.OU1 & self.OL5
        self.FUSTH <<= self.OU5 & self.OL5
        self.FUOR <<= self.OU4 & self.OL9
        self.FUSTS <<= self.OU4 & self.OL7
        self.FUWAIT <<= self.OU2 & self.OLE
        self.FUXW <<= self.OU4 & self.OL6

        self.FABC <<= (self.OU6 & self.O4 & self.NO5 & self.NO6)
        self.FABOX <<= (self.OU6 & self.OL3) | (self.O1 & self.NO3 & self.NO4 & self.NO5 & self.NO6)
        self.FABR <<= (self.OU6 & self.NO4 & self.O5 & self.NO6)
        self.FACAL <<= (self.OU0 & self.NO4 & self.O5)
        self.FACV <<= (self.OU2 & self.O4 & self.NO5 & self.NO6)
        self.FADE <<= (self.OU7 & self.OU4) | (self.OU7 & self.NO4 & self.O5 & self.O6)
        self.FADIV <<= (self.OU5 & self.OL0) | (self.OU3 & self.OL6)
        self.FADW <<= self.OU1 | (self.OU0 & self.O4)
        self.FAFL <<= (self.NO1 & self.O3 & self.O4 & self.O5)
        self.FAFLD <<= (self.NO1 & self.O3 & self.OLE)
        self.FAFLM <<= (self.NO1 & self.O3 & self.OLF)
        self.FAFRR <<= (self.OU2 & self.OL3) | (self.OU2 & self.OL5) | (self.OU1 & self.OL5)
        self.FAFRR_1 <<= (self.OU3 & self.NO4 & self.O5 & self.O6) | (self.OU4 & self.OL7) | (self.OU1 & self.OLF)
        self.FAILL <<= (self.OU5 & self.O4 & self.O5) | (self.NO1 & self.O3 & self.OL4) | (self.OU0 & self.NO4 & self.NO5 & self.NO6) | (self.NO2 & self.NO3 & self.OL3) | (self.O1 & self.NO3 & self.OL2) | (self.OU5 & self.O4 & self.NO6 & self.O7) | (self.OU5 & self.O5 & self.NO6 & self.NO7) | (self.OU1 & self.NO4 & self.O5 & self.O6) | (self.NO1 & self.NO3 & self.O4 & self.O5 & self.O6) | (self.OU2 & self.NO4 & self.O5 & self.O6) | (self.IA & self.NO3 & self.NO4 & self.NO5)
        self.FAIM <<= (self.NO3 & self.NO4 & self.NO5)
        self.FAIO <<= (self.OU4 & self.O4 & self.O5) | (self.OU6 & self.OLE)
        self.FAMDSF <<= self.FAMUL | self.FADIV | self.FASH | self.FAFL | self.SDIS
        self.FAMDSF_D <<= self.FADIV | self.FAFLD
        self.FAMUL <<= (self.OU5 & self.OL7) | (self.OU3 & self.OLT) | (self.OU2 & self.OL3)
        self.FANIMP <<= (self.NO1 & self.O3 & self.O4 & self.O5 & self.NFPOPTION) | (self.OU7 & self.O4 & self.NDEOPTION) | (self.OU7 & self.NO4 & self.O5 & self.O6 & self.NDEOPTION) | (self.FUEBS & self.NIA & self.NDEOPTION)
        self.FAPRIV <<= (self.NO3 & self.O4 & self.O5)
        self.FAPSD <<= (self.OU0 & self.O4 & self.O5 & self.O6)
        self.FARWD <<= (self.OU6 & self.O4 & self.O5 & self.O6)
        self.FAS1 <<= (self.NO1 & self.O3 & self.OL5)
        self.FAS2 <<= (self.OU1 & self.OL8) | (self.OU1 & self.OL1)
        self.FAS3 <<= (self.OU1 & self.NO5 & self.NO6 & self.NO7)
        self.FAS6 <<= (self.OU4 & self.NO4 & self.O5 & self.O7) | (self.OUH & self.OLA)
        self.FAS7 <<= (self.O2 & self.O3 & self.OL3) | (self.O1 & self.O3 & self.OL3)
        self.FAS8 <<= (self.OU3 & self.OL3) | (self.OU6 & self.OL6)
        self.FAS9 <<= (self.OU4 & self.OL6) | (self.OU4 & self.O4 & self.NO5 & self.NO6) | (self.OU4 & self.O4 & self.NO5 & self.O7)
        self.FAS10 <<= (self.OU3 & self.OLB & self.OU5 & self.OLB)
        self.FAS11 <<= (self.NO1 & self.O2 & self.OL1) | (self.O1 & self.O3 & self.OL1)
        self.FAS12 <<= (self.NO1 & self.O2 & self.OL0) | (self.OU3 & self.NO5 & self.NO6 & self.NO7) | (self.OU5 & self.NO5 & self.NO6 & self.NO7)
        self.FAS13 <<= (self.O1 & self.O3 & self.OL3)
        self.FAS14 <<= (self.OU4 & self.OL7) | (self.OU1 & self.OL5)
        self.FAS15 <<= (self.OU4 & self.OL5) | (self.OU4 & self.OLA)
        self.FAS16 <<= (self.OU1 & self.O4 & self.NO5 & self.O6) | (self.OU1 & self.NO5 & self.O6 & self.NO7)
        self.FAS17 <<= (self.OU0 & self.OL2) | (self.OU7 & self.OL0)
        self.FAS18 <<= (self.OU7 & self.NO4 & self.O5 & self.NO6) | (self.O2 & self.O3 & self.OL5) | (self.O1 & self.O3 & self.OL5)
        self.FAS19 <<= (self.OU1 & self.O4 & self.NO5 & self.O6)
        self.FAS21 <<= self.FAS10 | self.FAS23
        self.FAS22 <<= (self.OU1 & self.NO5 & self.NO6) | (self.NO1 & self.O3 & self.OL0)
        self.FAS23 <<= (self.OU5 & self.NO5 & self.O6 & self.NO7) | (self.O1 & self.O3 & self.OL2) | (self.NO1 & self.O2 & self.OL2) | (self.OU3 & self.NO5 & self.O6 & self.NO7)
        self.FAS24 <<= (self.OU6 & self.OL6) | (self.O2 & self.O3 & self.OL3) | (self.O1 & self.O3 & self.OL3)
        self.FAS26 <<= (self.OU3 & self.O4 & self.NO5 & self.NO6)
        self.FASH <<= (self.OU2 & self.NO4 & self.O5 & self.NO6)
        self.FASHFL <<= (self.FASH & self.NO7)
        self.FASHFX <<= (self.FASH & self.O7)
        self.FAST_1 <<= (self.OU0 & self.O4 & self.NO5) | (self.OU1 & self.OL3) | (self.OU2 & self.OLA) | (self.OU2 & self.OLB & self.OU3) | (self.NO3 & self.NO4 & self.O5)
        self.FAW <<= self.OU3 | (self.NO3 & self.NO4 & self.O5)
